name: Test build

on:
  pull_request:
    branches: [ master ]

jobs:
    deploy:
        name: Build Docker image and test container
        runs-on: ubuntu-latest
        steps:

        - name: Checkout repository
          uses: actions/checkout@v2

        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v0'

        - name: 'Output default GCP credentials to file'
          run: 'echo "$key" > key.json'
          shell: bash
          env:
            key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Build Docker image
          run: docker build . -t buildtest

        - name: Test Docker image
          run: docker run -e NODE_ENV=buildtest buildtest